### PR TITLE
Add MacOS aarch64-apple-darwin runner based on FlyCI

### PR DESCRIPTION
**Pull request by hubcio**

### CODE REVIEW

**Review by BartoszCiesla — DISMISSED** [review]

**Comment by kgantchev** [comment]
Hi @hubcio, 

My name is Kiril Gantchev, I'm the CEO and co-founder of [FlyCI](https://flyci.net). I'm super excited about the fact that the Iggy.rs team has decided to give FlyCI a shot and I would personally like to thank you! 

So far, I see that FlyCI's MacOS run is nearly 2x faster than [with GitHub's MacOS runner](https://github.com/iggy-rs/iggy/actions/runs/7513325330/job/20455072587?pr=539): **5 min 33 sec with FlyCI** vs **9 min 5 sec with GitHub**!

image

image

We hope that you're happy with the results. Please let us know if you run into any issues. Our team is always available should you have any questions. 

Quick question: how did you hear about FlyCI?

**Comment by hubcio** [comment]
Hello @kgantchev!
`iggy` was developed by @spetz on M1 Max machine, then I joined with my x86 Linux. Other devs are working on Linux and even lately we saw PR that someone was fixing Windows tests. Our tests, unfortunately, sometimes revealed bugs specific to one system that were inadvertently introduced by developers working on another.  So we concluded that we need to always test everything.

Answering your question, I was just googling for M1 runners, and I saw your service so I decided to give it a shot.

**Very good experience!**

To be honest, I didn't expect it to work first time 😅 

Thank you!

**Comment by kgantchev** [comment]
Awesome, thanks @hubcio !

**Comment by hubcio** [comment]
@kgantchev since you are already there, do u have any idea why right now it's waiting for runner more than 30 mins? 😅 
image

**Comment by kgantchev** [comment]
> @kgantchev since you are already there, do u have any idea why right now it's waiting for runner more than 30 mins? 😅  

Checking right now.

**Comment by kgantchev** [comment]
@hubcio Sorry... this is embarrassing, the M1 runners are very popular and we seem to be running out of capacity. 😅😅 

We're working to bring up more capacity now and your run should be completed automatically.

Another workaround may be to use our M2 runners: `flyci-macos-large-latest-m2` And not to worry, we still don't have billing enabled so you won't be billed for the M2 time. You can use all the runners for free until we enable billing (it will take us about a month). Once we enable billing, the M2 runners will stop working and you can switch back to M1.

**Comment by hubcio** [comment]
@kgantchev Alright, thanks for info 😄 I will make the job non-blocking tomorrow.

**Comment by kgantchev** [comment]
> @kgantchev Alright, thanks for info 😄 I will make the job non-blocking tomorrow.

No worries, you might not even have to do that. We're bring up more capacity so you might not even have to worry about this. :)

**Review by BartoszCiesla — APPROVED** [review]

**Comment by radeva** [comment]
Hi @hubcio @spetz

Thank you for being a FlyCI customer! We would love to get your feedback and add it to [our case studies section](https://www.flyci.net/case-studies?utm_source=github&utm_medium=community&utm_campaign=recommend). Are you open to sharing your feedback about FlyCI and getting your project highlighted in our case studies section?

- What motivated your choice to use FlyCI's MacOS runners, and what key benefits have you observed?(Performance, compatibility, etc.)

- What has been your experience with the FlyCI runners so far?

- What improvements have you noticed since integrating FlyCI's MacOS runners?(e.g., performance enhancements, reduced build times, developer productivity, cost savings)

**Pull request merged**
