### PR TITLE
[DRAFT] [IGGY-219] Test `examples` in CI

### PR DESCRIPTION
**Pull request by dfy313**
# **PR Submission Guidelines**

**Please remove this entire section before submitting your PR.**
**This section is only for your reference.**

🙌 **Thank you for contributing to `iggy`!**

To help us incorporate your changes efficiently, please adhere to the following guidelines:

## General Coding Remarks

- **Code Linting**: Run `rustfmt` to ensure your code adheres to the project's style.
- **Unit Testing**: Write or update unit tests to cover your changes.
- **Integration Testing**: Write or update integration tests to cover your changes.
- **Project Structure**: Follow the `iggy` project's structure and coding style.
- **Build Integrity**: Ensure your code compiles and runs error-free.

## Commit Message Rules

- **Description**: Provide a concise description of the changes.
- **Tags**: Avoid using GitHub tags like `feat:` or `chore:`.
- **Style**: Use an imperative style in the subject line (e.g., "Fix bug" rather than "Fixed bug" or "Fixes bug").
- **Brevity**: Keep the subject line under 80 characters.
- **Rationale**: Explain the 'why' and 'what' of your changes in the summary.
- **Details**: Use the body to elaborate on the 'how' of your changes.
- **Context**: Include 'before' and 'after' scenarios if applicable.
- **References**: Link any relevant issues or PRs in the message body.

**Remember:** Your contribution is essential to the success of `iggy`. Please ensure that your PR conforms to these guidelines for a swift and smooth integration process.

Thank you!

### CODE REVIEW

**Comment by numinnex** [comment]
Hello, first of all, thank you for contributing to our project! You don't have to include the contribution guidelines in the PR description instead, it would be preferable to pinpoint which issue this pull request addresses (e.g Closes #219).

 On top of that, this isn't really what we've envisioned when creating this issue, we would like to integration test scenarios from examples, instead of mocking the client.

If you have any questions regarding this issue, or Iggy in general join our discord, we can help you there more directly.

**Comment by dfy313** [comment]
> Hello, first of all, thank you for contributing to our project! You don't have to include the contribution guidelines in the PR description, instead it would be preferable to pinpoint which issue this pull request addresses (e.g Closes #219).
> 
> On top of that, this isn't really what we've envisioned when creating this issue, we would like to integration test scenarios from `examples`, instead of mocking the client.
> 
> If you have any questions regarding this issue, or Iggy in general join our discord, we can help you there more directly.

@numinnex Thanks for the feedback! I definitely should have reached out in the discord before diving into this. I'll close out this issue for now and work on adding some integration tests for the scenarios in examples.

**Comment by hubcio** [comment]
@dfy313 the examples should be runnable in the CI via `cargo run --example XXXX` :) what's your username on discord?

**Comment by dfy313** [comment]
> @dfy313 the examples should be runnable in the CI via `cargo run --example XXXX` :) what's your username on discord?

@hubcio discord username is also dfy313 :)

**Pull request closed without merging**
