### PR TITLE
use `keepcalm` instead of `Arc<RwLock<System>>`

### PR DESCRIPTION
**Pull request by berendsliedrecht**
- Uses keepcalms `SharedMut` which is equivalent to `Arc<RwLock<T>>`.
- acquiring the lock is now sync so this PR mainly consisted of removing the `await` calls.
- Can likely be done for more usages of `Arc<RwLock<T>>` (or any `Arc<T>` in general) if that is desired.
- Closes #123 Although it might be good to use this in more locations.

### CODE REVIEW

**Comment by hubcio** [comment]
Didn't you use `sync` version of `keepcalm`? Could you verify performance like you did in #420 (nice)? :D thanks!

**Comment by berendsliedrecht** [comment]
bench cmd: `cargo r -r -- -c -v send --message-size 2000 --messages-per-batch 1000 --message-batches 1000 --producers 5 --streams 5 tcp` (using release mode now... makes more sense.)

With `keepcalm`

```
2023-12-29T17:42:52.916889Z  INFO iggy_bench::benchmarks::send_benchmark: Benchmark: send messages, total messages: 5000000, total size: 10000000000 bytes, 5 streams, 1000 messages per batch, 1000 batches, 2000 bytes per message, 5 producers

2023-12-29T17:42:52.916946Z  INFO iggy_bench::benchmark_runner: Results: total throughput: 1715.98 MB/s, 857991 messages/s, average latency: 5.83 ms, average  throughput: 343.20 MB/s, total duration: 5.83 s
```

with `tokio` 

```
2023-12-29T17:51:51.187092Z  INFO iggy_bench::benchmarks::send_benchmark: Benchmark: send messages, total messages: 5000000, total size: 10000000000 bytes, 5 streams, 1000 messages per batch, 1000 batches, 2000 bytes per message, 5 producers

2023-12-29T17:51:51.187120Z  INFO iggy_bench::benchmark_runner: Results: total throughput: 1686.93 MB/s, 843463 messages/s, average latency: 5.93 ms, average  throughput: 337.39 MB/s, total duration: 5.93 s
```

There seems to be a negligible gain in perf, and a binary size decrease of the server from 11840928 to 11787232 which is a nice side-effect I guess :).


> Didn't you use sync version of `keepcalm`?

I did use the sync version, which is why I had to remove the await calls. They do have an async variant, but they mentioned it is experimental / might have performance issues.

**Comment by hubcio** [comment]
Well, it's weird that `sync` version seems to be faster than `async` :D Anyway, I will verify those tomorrow on my machine (5950x, PCIE 4.0 NVME SSD), so if everything's good, we will merge.

Just a side question:
What do you think about using jemalloc? Do you have any experience with it?

**Comment by berendsliedrecht** [comment]
> Well, it's weird that `sync` version seems to be faster than `async` :D Anyway, I will verify those tomorrow on my machine (5950x, PCIE 4.0 NVME SSD), so if everything's good, we will merge.
> 

Yeah, async can always be a bit of a hit or miss in my experience. But, yeah it would be good to do some additional tests for this.

> Just a side question: What do you think about using jemalloc? Do you have any experience with it?

I don't have any first-hand experience with it. It is being used in another project I work, though. Do you think that this would be something worth checking out for the server? I might have some time to check it out.

**Comment by hubcio** [comment]
I actually did some tests with it, performance has been more or less the same (-+ 1%), but the memory usage stability was much better, no jumps in RSS usage so that's good. Let's continue under #424.

**Comment by spetz** [comment]
I've just ran the benchmarks for both solutions and have seen the similar results (as already mentioned), which I find kind of surprising, that there's almost no difference between the `sync` and `async` versions :)

**Review by hubcio — APPROVED** [review]

**Pull request merged**
