### PR TITLE
fix: place generated file in OUT_DIR

### PR DESCRIPTION
**Pull request by daniel-pape**
Should fix issue #78

### CODE REVIEW

**Comment by spetz** [comment]
Hello Daniel, thanks for the changes :)

I've just tried running the `cargo publish -p iggy` and got the same error:

```
error: failed to verify package tarball

Caused by:
  Source directory was modified by build.rs during cargo publish. Build scripts should not modify anything outside of OUT_DIR.
```

Also, when I tried to simply build the project with `cargo build` I did receive:

```
error: couldn't read /Users/piotr/Workspace/Iggy/iggy/target/debug/build/iggy-5339cf861c821228/out/error.rs: No such file or directory (os error 2)
 --> iggy/src/errors/mod.rs:1:1
  |
1 | include!(concat!(env!("OUT_DIR"), "/error.rs"));
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

BTW one small warning from clippy - not needed `use std::io::Write;` in`build.rs`.

**Comment by hubcio** [comment]
Just small nitpick, use #78 instead of `78`, github will nicely link these references (issue and pull requests).

**Comment by daniel-pape** [comment]
> Hello Daniel, thanks for the changes :)
> 
> I've just tried running the `cargo publish -p iggy` and got the same error:
> 
> ```
> error: failed to verify package tarball
> 
> Caused by:
>   Source directory was modified by build.rs during cargo publish. Build scripts should not modify anything outside of OUT_DIR.
> ```
> 
> Also, when I tried to simply build the project with `cargo build` I did receive:
> 
> ```
> error: couldn't read /Users/piotr/Workspace/Iggy/iggy/target/debug/build/iggy-5339cf861c821228/out/error.rs: No such file or directory (os error 2)
>  --> iggy/src/errors/mod.rs:1:1
>   |
> 1 | include!(concat!(env!("OUT_DIR"), "/error.rs"));
>   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ```
> 
> BTW one small warning from clippy - not needed `use std::io::Write;` in`build.rs`.

Hello Piotr, 

Could you try to delete the directory `/iggy/errors_table/` so that the check https://github.com/iggy-rs/iggy/blob/fdde1f9e477eec80c4dba552d8be99ec2ecc6154/iggy/build.rs#L192 is skipped? Otherwise the new file in OUT_DIR is not created and the updated `include!` cannot find it.

**Comment by spetz** [comment]
It builds now, however still no luck with `cargo publish` - I did remove the mentioned `errors_table` directory, also ran `cargo clean` etc. but still got the same issue.

**Comment by daniel-pape** [comment]
> It builds now, however still no luck with `cargo publish` - I did remove the mentioned `errors_table` directory, also ran `cargo clean` etc. but still got the same issue.

I will take a look.

**Comment by daniel-pape** [comment]
> > It builds now, however still no luck with `cargo publish` - I did remove the mentioned `errors_table` directory, also ran `cargo clean` etc. but still got the same issue.
> 
> I will take a look.

I decided to remove the Sled part and load the Errors directly via a function call. One reason for doing so was do avoid creating additional directories/files (which might cause issues depending on where it is done) and the other one was that we already discussed that Sled instead of relational DB does not provided any additional benefit. With this it now seems to work fine. Initially, I was not aware of the `dry-run` option of `cargo publish` and relied (implicitly) on everything working if it works for `cargo build`.

**Comment by spetz** [comment]
Thanks, it's almost working now :D I'm getting some weird error (hopefully the last one):

```
Caused by:
  Source directory was modified by build.rs during cargo publish. Build scripts should not modify anything outside of OUT_DIR.
  Changed: /iggy/target/package/iggy-0.0.85/src/users/mod.rs
```

Not sure how it has to do anything with the `users` module?

**Comment by spetz** [comment]
You could also try to rebase the latest master branch and run the `cargo fmt` - maybe it has something to do with the recently merged user defaults file?

**Comment by hubcio** [comment]
@daniel-pape we will merge today, after out CI improvements (we will now have clippy, rustfmt and semver checks before merge)

**Review by spetz — APPROVED** [review]

**Pull request merged**
